[package]
name = "pbr"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.29"
wgpu = "0.19"
pollster = "0.3"
glam = "0.30.10"
encase = { version = "0.11.1", features = ["glam"] }
bytemuck = { version = "1.14", features = ["derive"] }
